sonar.projectKey=ntu-cloudnative-pms
sonar.sources=frontend/src/app,backend/src/main/java
sonar.java.binaries=backend/target/classes
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.tests=frontend/src/test, backend/src/test